### PR TITLE
istioctl version test

### PR DESCRIPTION
**Pull request by chxchx**
Example output from `./istioctl version`
```
 $ ./istioctl version
Version: master-20180523-09-15
GitRevision: 23d2f39c506deaae382994154b3ad19f6e5ee932
User: root@d921879332bc
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean
```

This PR adds assertion to ensure hub points to gcr. Let me know if this is enough. Also, I can't seem to find release artifacts marked as TESTONLY from https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/. Am I missing something? Is the OKR "Add release binary test to ensure the right binaries (i.e. not debug) are released." still pertinent here?

### CODE REVIEW

**Comment by rkpagadala** [comment]
@chxchx  "Add release binary test to ensure the right binaries (i.e. not debug) are released." is still pertinent. TESTONLY has been dropped as part of the name, the tarballs at the top are the same as testonly, they are also available under gcr.io. You could also test that the istioctl in docker.io/* points to docker.io

**Comment by hklai** [comment]
I think the assertion should be the version string matching an expected version, which comes as an input from the release pipeline.

**Comment by chxchx** [comment]
@hklai @rkpagadala PTAL
The test failures are unrelated to this PR. In fact, the istioctl version checks added in this PR are run before any e2e tests, and are working fine.

**Comment by chxchx** [comment]
fixes https://github.com/istio/istio/issues/2784

**Pull request merged**
